<?php
// This file generated by Propel 1.5.2-dev convert-conf target
// from XML runtime conf file /opt/lampp/htdocs/gepi/orm/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'gepi' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'classname' => 'DebugPDO',
        'dsn' => 'mysql:dbname='.$GLOBALS["dbDb"].';host='.$GLOBALS["dbHost"],
        'user' => $GLOBALS["dbUser"],
        'password' => $GLOBALS["dbPass"],
        'options' => 
        array (
          'ATTR_PERSISTENT' => 
          array (
            'value' => false,
          ),
        ),
        'attributes' => 
        array (
          'ATTR_EMULATE_PREPARES' => 
          array (
            'value' => true,
          ),
        ),
        'settings' => 
        array (
          'charset' => 
          array (
            'value' => 'Latin1',
          ),
        ),
      ),
    ),
    'default' => 'gepi',
  ),
  'generator_version' => '1.5.2-dev',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-gepi-conf.php');
return $conf;