<?php
// This file generated by Propel 1.3.0 convert-props target
return array (
  'propel' => 
  array (
    'datasources' => 
    array (
      'gepi' => 
      array (
        'classes' => 
        array (
          'UtilisateurMapBuilder' => 'gepi/map/UtilisateurMapBuilder.php',
          'UtilisateurPeer' => 'gepi/UtilisateurPeer.php',
          'Utilisateur' => 'gepi/Utilisateur.php',
          'CtCompteRenduMapBuilder' => 'gepi/map/CtCompteRenduMapBuilder.php',
          'CtCompteRenduPeer' => 'gepi/CtCompteRenduPeer.php',
          'CtCompteRendu' => 'gepi/CtCompteRendu.php',
          'CtDocumentMapBuilder' => 'gepi/map/CtDocumentMapBuilder.php',
          'CtDocumentPeer' => 'gepi/CtDocumentPeer.php',
          'CtDocument' => 'gepi/CtDocument.php',
          'CtTravailAFaireMapBuilder' => 'gepi/map/CtTravailAFaireMapBuilder.php',
          'CtTravailAFairePeer' => 'gepi/CtTravailAFairePeer.php',
          'CtTravailAFaire' => 'gepi/CtTravailAFaire.php',
          'CtDevoirDocumentMapBuilder' => 'gepi/map/CtDevoirDocumentMapBuilder.php',
          'CtDevoirDocumentPeer' => 'gepi/CtDevoirDocumentPeer.php',
          'CtDevoirDocument' => 'gepi/CtDevoirDocument.php',
          'GroupeMapBuilder' => 'gepi/map/GroupeMapBuilder.php',
          'GroupePeer' => 'gepi/GroupePeer.php',
          'Groupe' => 'gepi/Groupe.php',
          'JGroupesProfesseursMapBuilder' => 'gepi/map/JGroupesProfesseursMapBuilder.php',
          'JGroupesProfesseursPeer' => 'gepi/JGroupesProfesseursPeer.php',
          'JGroupesProfesseurs' => 'gepi/JGroupesProfesseurs.php',
          'ClasseMapBuilder' => 'gepi/map/ClasseMapBuilder.php',
          'ClassePeer' => 'gepi/ClassePeer.php',
          'Classe' => 'gepi/Classe.php',
          'JGroupesClassesMapBuilder' => 'gepi/map/JGroupesClassesMapBuilder.php',
          'JGroupesClassesPeer' => 'gepi/JGroupesClassesPeer.php',
          'JGroupesClasses' => 'gepi/JGroupesClasses.php',
        ),
      ),
    ),
  ),
);