<?php
// This file generated by Propel 1.3.0 convert-props target
// from XML runtime conf file /var/www/gepitrunk/orm/runtime-conf.xml
return array_merge_recursive(array (
  'propel' => 
  array (
    'datasources' => 
    array (
      'gepi' => 
      array (
        'adapter' => 'mysql',
        'connection' => 
        array (
          'classname' => 'DebugPDO',
          'dsn' => 'mysql:dbname='.$GLOBALS["dbDb"].';host='.$GLOBALS["dbHost"],
          'user' => $GLOBALS["dbUser"],
          'password' => $GLOBALS["dbPass"],
          'options' => 
          array (
            'ATTR_PERSISTENT' => 
            array (
              'value' => false,
            ),
          ),
          'attributes' => 
          array (
            'ATTR_EMULATE_PREPARES' => 
            array (
              'value' => true,
            ),
          ),
          'settings' => 
          array (
            'charset' => 
            array (
              'value' => 'Latin1',
            ),
          ),
        ),
      ),
      'default' => 'gepi',
    ),
    'generator_version' => '1.3.0',
  ),
), include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'gepi-classmap.php'));