INSERT INTO utilisateurs SET login = 'ADMIN', nom = 'GEPI', prenom = 'Administrateur', civilite = 'M.', password = 'ab4f63f9ac65152575886860dde480a1', statut = 'administrateur', etat = 'actif', change_mdp = 'y';
INSERT INTO setting VALUES ('version', '1.5.0');
INSERT INTO setting VALUES ('versionRc', '');
INSERT INTO setting VALUES ('versionBeta', '1');
INSERT INTO setting VALUES ('sessionMaxLength', '30');
INSERT INTO setting VALUES ('Impression','<center><p class = \"grand\">Gestion des Elèves Par Internet</p></center>\r\n<br />\r\n<p class = \"grand\">Qu\'est-ce que GEPI ?</p>\r\n\r\n<p>Afin d\'étudier les modalités d\'informatisation des bulletins scolaires : notes et appréciations via Internet, une expérimentation (baptisée Gestion des Elèves Par Internet)a été mise en place. Cette expérimentation concerne les classes suivantes : \r\n<br />* ....\r\n<br />* ....\r\n<br />\r\n<br />\r\nCeci vous concerne car vous êtes professeur enseignant dans l\'une ou l\'autre de ces classes.\r\n<br />\r\n<br />\r\nA partir de la réception de ce document, vous pourrez remplir les bulletins informatisés :\r\n<span class = \"norme\">\r\n<UL><li>soit au lycée à partir de n\'importe quel poste connecté à Internet,\r\n<li>soit chez vous si vous disposez d\'une connexion Internet.\r\n</ul>\r\n</span>\r\n<p class = \"grand\">Comment accéder au module de saisie (notes etappréciations) :</p>\r\n<span class = \"norme\">\r\n<UL>\r\n    <LI>Se connecter à Internet\r\n    <LI>Lancer un navigateur (FireFox de préférence, Opera, Internet Explorer, ...)\r\n    <LI>Se connecter au site : https://adresse_du_site/gepi\r\n    <LI>Après quelques instants une page apparaît vous invitant à entrer un nom d\'identifiant et un mot de passe (cesinformations figurent en haut de cette page).\r\n    <br />ATTENTION : votre mot de passe est strictement confidentiel.\r\n    <br />\r\n    <br />Une fois ces informations fournies, cliquez sur le bouton \"Ok\".\r\n    <LI> Après quelques instants une page d\'accueil apparaît.<br />\r\nLa première fois, Gepi vous demande de changer votre mot de passe.\r\nChoisissez-en un facile à retenir, mais non trivial (évitez toute date\r\nde naissance, nom d\'animal familier, prénom, etc.), et contenant\r\nlettre(s), chiffre(s), et caractère(s) non alphanumérique(s).<br />\r\nLes fois suivantes, vous arriverez directement au menu général de\r\nl\'application. Pour bien prendre connaissance des possibilités de\r\nl\'application, n\'hésitez pas à essayer tous les liens disponibles !\r\n</ul></span>\r\n<p class = \"grand\">Remarque :</p>\r\n<p>GEPI est prévu pour que chaque professeur ne puisse modifier les notes ou les appréciations que dans les rubriques qui le concernent et uniquement pour ses élèves.\r\n<br />\r\nJe reste à votre disposition pour tout renseignement complémentaire.\r\n    <br />\r\n    Le proviseur adjoint\r\n</p>');
INSERT INTO setting VALUES ('gepiYear', '2006/2007');
INSERT INTO setting VALUES ('gepiSchoolName', 'Nom du Lycée');
INSERT INTO setting VALUES ('gepiSchoolAdress1', 'Adresse');
INSERT INTO setting VALUES ('gepiSchoolAdress2', 'Boîte postale');
INSERT INTO setting VALUES ('gepiSchoolZipCode', 'Code postal');
INSERT INTO setting VALUES ('gepiSchoolCity', 'Ville');
INSERT INTO setting VALUES ('gepiAdminAdress', 'email.admin@gepi.fr');
INSERT INTO setting VALUES ('titlesize', '14');
INSERT INTO setting VALUES ('textsize', '8');
INSERT INTO setting VALUES ('cellpadding', '3');
INSERT INTO setting VALUES ('cellspacing', '1');
INSERT INTO setting VALUES ('largeurtableau', '800');
INSERT INTO setting VALUES ('col_matiere_largeur', '150');
INSERT INTO setting VALUES ('begin_bookings', '1157058000');
INSERT INTO setting VALUES ('end_bookings', '1188594000');
INSERT INTO setting VALUES ('max_size', '307200');
INSERT INTO setting VALUES ('total_max_size', '5242880');
INSERT INTO setting VALUES ('col_note_largeur', '30');
INSERT INTO setting VALUES ('active_cahiers_texte', 'y');
INSERT INTO setting VALUES ('active_carnets_notes', 'y');
INSERT INTO setting VALUES ('active_observatoire', 'n');
INSERT INTO setting VALUES ('logo_etab', 'logo.gif');
INSERT INTO setting VALUES ('longmin_pwd', '5');
INSERT INTO setting VALUES ('duree_conservation_logs', '365');
INSERT INTO setting VALUES ('GepiRubConseilProf', 'yes');
INSERT INTO setting VALUES ('GepiRubConseilScol', 'yes');
INSERT INTO setting VALUES ('bull_ecart_entete', '0');
INSERT INTO setting VALUES ('gepi_prof_suivi', 'professeur principal');
INSERT INTO setting VALUES ('GepiProfImprBul', 'no');
INSERT INTO setting VALUES ('GepiProfImprBulSettings', 'no');
INSERT INTO setting VALUES ('GepiScolImprBulSettings', 'yes');
INSERT INTO setting VALUES ('GepiAdminImprBulSettings', 'no');
INSERT INTO setting VALUES ('GepiAccesReleveScol', 'yes');
INSERT INTO setting VALUES ('GepiAccesReleveCpe', 'no');
INSERT INTO setting VALUES ('GepiAccesReleveProf', 'no');
INSERT INTO setting VALUES ('GepiAccesReleveProfTousEleves', 'no');
INSERT INTO setting VALUES ('GepiAccesReleveProfP', 'yes');
INSERT INTO setting VALUES ('page_garde_imprime', 'no');
INSERT INTO setting VALUES ('page_garde_texte', 'Madame, Monsieur<br/><br/>Veuillez trouvez ci-joint le bulletin scolaire de votre enfant. Nous vous rappelons que la journ&eacute;e <span style="font-weight: bold;">Portes ouvertes</span> du Lyc&eacute;e aura lieu samedi 20 mai entre 10 h et 17 h.<br/><br/>Veuillez agr&eacute;er, Madame, Monsieur, l''expression de mes meilleurs sentiments.<br/><br/><div style="text-align: right;">Le proviseur</div>');
INSERT INTO setting VALUES ('page_garde_padding_top', '4');
INSERT INTO setting VALUES ('page_garde_padding_left', '11');
INSERT INTO setting VALUES ('page_garde_padding_text', '6');
INSERT INTO setting VALUES ('addressblock_padding_top', '40');
INSERT INTO setting VALUES ('addressblock_padding_right', '20');
INSERT INTO setting VALUES ('addressblock_padding_text', '20');
INSERT INTO setting VALUES ('addressblock_length', '60');
INSERT INTO setting VALUES ('bull_espace_avis', '5');
INSERT INTO setting VALUES ('change_ordre_aff_matieres', 'ok');
INSERT INTO setting VALUES ('disable_login', 'no');
INSERT INTO setting VALUES ('bull_formule_bas', 'Bulletin à conserver précieusement. Aucun duplicata ne sera délivré. - GEPI : solution libre de gestion et de suivi des résultats scolaires.');
INSERT INTO setting VALUES ('delai_devoirs', '7');
INSERT INTO setting VALUES ('active_module_absence', 'y');
INSERT INTO setting VALUES ('active_module_absence_professeur', 'y');
INSERT INTO setting VALUES ('gepiSchoolTel', '00 00 00 00 00');
INSERT INTO setting VALUES ('gepiSchoolFax', '00 00 00 00 00');
INSERT INTO setting VALUES ('gepiSchoolEmail', 'ce.XXXXXXXX@ac-xxxxx.fr');
INSERT INTO setting VALUES ('col_boite_largeur', '120');
INSERT INTO setting VALUES ('bull_mention_doublant', 'no');
INSERT INTO setting VALUES ('bull_affiche_numero', 'no');
INSERT INTO setting VALUES ('nombre_tentatives_connexion', '10');
INSERT INTO setting VALUES ('temps_compte_verrouille', '30');
INSERT INTO setting VALUES ('bull_affiche_appreciations', 'y');
INSERT INTO setting VALUES ('bull_affiche_absences', 'y');
INSERT INTO setting VALUES ('bull_affiche_avis', 'y');
INSERT INTO setting VALUES ('bull_affiche_aid', 'y');
INSERT INTO setting VALUES ('bull_affiche_formule', 'y');
INSERT INTO setting VALUES ('bull_affiche_signature', 'y');
INSERT INTO setting VALUES ('l_max_aff_trombinoscopes', '120');
INSERT INTO setting VALUES ('h_max_aff_trombinoscopes','160');
INSERT INTO setting VALUES ('l_max_imp_trombinoscopes', '70');
INSERT INTO setting VALUES ('h_max_imp_trombinoscopes','100');
INSERT INTO setting VALUES ('active_module_msj', 'n');
INSERT INTO setting VALUES ('site_msj_gepi', 'http://gepi.sylogix.net/releases/');
INSERT INTO setting VALUES ('rc_module_msj', 'n');
INSERT INTO setting VALUES ('beta_module_msj', 'n');
INSERT INTO setting VALUES ('dossier_ftp_gepi', 'gepi');
INSERT INTO etablissements VALUES ('999', 'étranger', 'aucun', 'aucun', 999, '');
INSERT INTO droits VALUES ('/absences/index.php', 'F', 'F', 'V', 'F', 'F', 'F', 'V', 'Saisie des absences', '');
INSERT INTO droits VALUES ('/absences/saisie_absences.php', 'F', 'F', 'V', 'F', 'F', 'F', 'V', 'Saisie des absences', '');
INSERT INTO droits VALUES ('/accueil_admin.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', '', '');
INSERT INTO droits VALUES ('/accueil_modules.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', '', '');
INSERT INTO droits VALUES ('/accueil.php', 'V', 'V', 'V', 'V', 'V', 'V', 'V', '', '');
INSERT INTO droits VALUES ('/aid/add_aid.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration des AID', '');
INSERT INTO droits VALUES ('/aid/config_aid.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration des AID', '');
INSERT INTO droits VALUES ('/aid/export_csv_aid.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration des AID', '');
INSERT INTO droits VALUES ('/aid/help.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration des AID', '');
INSERT INTO droits VALUES ('/aid/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration des AID', '');
INSERT INTO droits VALUES ('/aid/index2.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration des AID', '');
INSERT INTO droits VALUES ('/aid/modify_aid.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration des AID', '');
INSERT INTO droits VALUES ('/bulletin/edit.php', 'F', 'V', 'F', 'V', 'F', 'F', 'F', 'Edition des bulletins', '1');
INSERT INTO droits VALUES ('/bulletin/index.php', 'F', 'V', 'F', 'V', 'F', 'F', 'F', 'Edition des bulletins', '1');
INSERT INTO droits VALUES ('/bulletin/param_bull.php', 'V', 'V', 'F', 'V', 'F', 'F', 'F', 'Edition des bulletins', '1');
INSERT INTO droits VALUES ('/bulletin/verif_bulletins.php', 'F', 'V', 'F', 'V', 'F', 'F', 'F', 'Vérification du remplissage des bulletins', '');
INSERT INTO droits VALUES ('/bulletin/verrouillage.php', 'F', 'F', 'F', 'V', 'F', 'F', 'F', '(de)Verrouillage des périodes', '');
INSERT INTO droits VALUES ('/cahier_notes_admin/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Gestion des carnets de notes', '');
INSERT INTO droits VALUES ('/cahier_notes/add_modif_conteneur.php', 'F', 'V', 'F', 'F', 'F', 'F', 'F', 'Carnet de notes', '1');
INSERT INTO droits VALUES ('/cahier_notes/add_modif_dev.php', 'F', 'V', 'F', 'F', 'F', 'F', 'F', 'Carnet de notes', '1');
INSERT INTO droits VALUES ('/cahier_notes/index.php', 'F', 'V', 'F', 'F', 'F', 'F', 'F', 'Carnet de notes', '1');
INSERT INTO droits VALUES ('/cahier_notes/saisie_notes.php', 'F', 'V', 'F', 'F', 'F', 'F', 'F', 'Carnet de notes', '1');
INSERT INTO droits VALUES ('/cahier_notes/toutes_notes.php', 'F', 'V', 'F', 'F', 'F', 'F', 'F', 'Carnet de notes', '1');
INSERT INTO droits VALUES ('/cahier_notes/visu_releve_notes.php', 'F', 'V', 'V', 'V', 'V', 'V', 'F', 'Visualisation et impression des relevés de notes', '');
INSERT INTO droits VALUES ('/cahier_texte_admin/admin_ct.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Gestion des cahier de texte', '');
INSERT INTO droits VALUES ('/cahier_texte_admin/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Gestion des cahier de texte', '');
INSERT INTO droits VALUES ('/cahier_texte_admin/modify_limites.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Gestion des cahier de texte', '');
INSERT INTO droits VALUES ('/cahier_texte_admin/modify_type_doc.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Gestion des cahier de texte', '');
INSERT INTO droits VALUES ('/cahier_texte/index.php', 'F', 'V', 'F', 'F', 'F', 'F', 'F', 'Cahier de texte', '1');
INSERT INTO droits VALUES ('/cahier_texte/traite_doc.php', 'F', 'V', 'F', 'F', 'F', 'F', 'F', 'Cahier de texte', '1');
INSERT INTO droits VALUES ('/classes/classes_ajout.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des classes', '');
INSERT INTO droits VALUES ('/classes/classes_const.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des classes', '');
INSERT INTO droits VALUES ('/classes/cpe_resp.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Affectation des CPE aux classes', '');
INSERT INTO droits VALUES ('/classes/duplicate_class.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des classes', '');
INSERT INTO droits VALUES ('/classes/eleve_options.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des classes', '');
INSERT INTO droits VALUES ('/classes/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des classes', '');
INSERT INTO droits VALUES ('/classes/init_options.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des classes', '');
INSERT INTO droits VALUES ('/classes/modify_class.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des classes', '');
INSERT INTO droits VALUES ('/classes/modify_nom_class.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des classes', '');
INSERT INTO droits VALUES ('/classes/modify_options.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des classes', '');
INSERT INTO droits VALUES ('/classes/periodes.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des classes', '');
INSERT INTO droits VALUES ('/classes/prof_suivi.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des classes', '');
INSERT INTO droits VALUES ('/classes/scol_resp.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Affectation des comptes scolarité aux classes', '');
INSERT INTO droits VALUES ('/eleves/help.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des élèves', '');
INSERT INTO droits VALUES ('/eleves/import_eleves_csv.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des élèves', '');
INSERT INTO droits VALUES ('/eleves/index.php', 'V', 'F', 'F', 'V', 'F', 'F', 'F', 'Gestion des élèves', '');
INSERT INTO droits VALUES ('/eleves/modify_eleve.php', 'V', 'F', 'F', 'V', 'F', 'F', 'F', 'Gestion des élèves', '');
INSERT INTO droits VALUES ('/etablissements/help.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des établissements', '');
INSERT INTO droits VALUES ('/etablissements/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des établissements', '');
INSERT INTO droits VALUES ('/etablissements/modify_etab.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des établissements', '');
INSERT INTO droits VALUES ('/groupes/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Edition des groupes', '');
INSERT INTO droits VALUES ('/groupes/add_group.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Ajout de groupes', '');
INSERT INTO droits VALUES ('/groupes/edit_group.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Edition de groupes', '');
INSERT INTO droits VALUES ('/groupes/edit_eleves.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Edition des élèves des groupes', '');
INSERT INTO droits VALUES ('/groupes/edit_class.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Edition des groupes de la classe', '');
INSERT INTO droits VALUES ('/gestion/accueil_sauve.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Restauration, suppression et sauvegarde de la base', '');
INSERT INTO droits VALUES ('/gestion/savebackup.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Téléchargement de sauvegardes la base', '');
INSERT INTO droits VALUES ('/gestion/efface_base.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Restauration, suppression et sauvegarde de la base', '');
INSERT INTO droits VALUES ('/gestion/gestion_connect.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Gestion des connexions', '');
INSERT INTO droits VALUES ('/gestion/help_import.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/gestion/help.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', '', '');
INSERT INTO droits VALUES ('/gestion/import_csv.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/gestion/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', '', '');
INSERT INTO droits VALUES ('/gestion/modify_impression.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Gestion des paramètres de la feuille de bienvenue', '');
INSERT INTO droits VALUES ('/gestion/param_gen.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration générale', '');
INSERT INTO droits VALUES ('/gestion/traitement_csv.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/init_csv/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation CSV de l\'année scolaire', '');
INSERT INTO droits VALUES ('/init_csv/eleves.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation CSV de l\'année scolaire', '');
INSERT INTO droits VALUES ('/init_csv/responsables.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation CSV de l\'année scolaire', '');
INSERT INTO droits VALUES ('/init_csv/disciplines.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation CSV de l\'année scolaire', '');
INSERT INTO droits VALUES ('/init_csv/professeurs.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation CSV de l\'année scolaire', '');
INSERT INTO droits VALUES ('/init_csv/eleves_classes.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation CSV de l\'année scolaire', '');
INSERT INTO droits VALUES ('/init_csv/prof_disc_classes.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation CSV de l\'année scolaire', '');
INSERT INTO droits VALUES ('/init_csv/eleves_options.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation CSV de l\'année scolaire', '');
INSERT INTO droits VALUES ('/init_scribe/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/init_scribe/professeurs.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/init_scribe/eleves.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/init_scribe/eleves_options.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/init_scribe/prof_disc_classes.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/init_scribe/disciplines.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/init_lcs/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation LCS de l''année scolaire', '');
INSERT INTO droits VALUES ('/init_lcs/eleves.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation LCS de l''année scolaire', '');
INSERT INTO droits VALUES ('/init_lcs/professeurs.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation LCS de l''année scolaire', '');
INSERT INTO droits VALUES ('/init_lcs/disciplines.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation LCS de l''année scolaire', '');
INSERT INTO droits VALUES ('/init_lcs/affectations.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation LCS de l''année scolaire', '');
INSERT INTO droits VALUES ('/initialisation/clean_tables.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/initialisation/disciplines.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/initialisation/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/initialisation/init_options.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/initialisation/prof_disc_classe.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/initialisation/professeurs.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/initialisation/responsables.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/initialisation/step1.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/initialisation/step2.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/initialisation/step3.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO droits VALUES ('/lib/confirm_query.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', '', '');
INSERT INTO droits VALUES ('/matieres/help.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des matières', '');
INSERT INTO droits VALUES ('/matieres/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des matières', '');
INSERT INTO droits VALUES ('/matieres/modify_matiere.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des matières', '');
INSERT INTO droits VALUES ('/matieres/matieres_param.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des classes', '');
INSERT INTO droits VALUES ('/matieres/matieres_categories.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Edition des catégories de matière', '');
INSERT INTO droits VALUES ('/prepa_conseil/edit_limite.php', 'V', 'V', 'V', 'V', 'V', 'V', 'F', 'Edition des bulletins simplifiés (documents de travail)', '');
INSERT INTO droits VALUES ('/prepa_conseil/help.php', 'V', 'V', 'V', 'V', 'F', 'F', 'F', '', '');
INSERT INTO droits VALUES ('/prepa_conseil/index1.php', 'F', 'V', 'F', 'V', 'F', 'F', 'F', 'Visualisation des notes et appréciations', '1');
INSERT INTO droits VALUES ('/prepa_conseil/index2.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Visualisation des notes par classes', '');
INSERT INTO droits VALUES ('/prepa_conseil/index3.php', 'F', 'V', 'V', 'V', 'V', 'V', 'F', 'Edition des bulletins simplifiés (documents de travail)', '');
INSERT INTO droits VALUES ('/prepa_conseil/visu_aid.php', 'F', 'V', 'F', 'F', 'F', 'F', 'F', 'Visualisation des notes et appréciations AID', '');
INSERT INTO droits VALUES ('/prepa_conseil/visu_toutes_notes.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Visualisation des notes par classes', '');
INSERT INTO droits VALUES ('/responsables/index.php', 'V', 'F', 'F', 'V', 'F', 'F', 'F', 'Configuration et gestion des responsables élèves', '');
INSERT INTO droits VALUES ('/responsables/modify_resp.php', 'V', 'F', 'F', 'V', 'F', 'F', 'F', 'Configuration et gestion des responsables élèves', '');
INSERT INTO droits VALUES ('/saisie/help.php', 'F', 'V', 'F', 'F', 'F', 'F', 'V', '', '');
INSERT INTO droits VALUES ('/saisie/import_class_csv.php', 'F', 'V', 'F', 'V', 'F', 'F', 'V', '', '');
INSERT INTO droits VALUES ('/saisie/import_note_app.php', 'F', 'V', 'F', 'F', 'F', 'F', 'V', '', '');
INSERT INTO droits VALUES ('/saisie/index.php', 'F', 'V', 'F', 'F', 'F', 'V', 'F', '', '');
INSERT INTO droits VALUES ('/saisie/saisie_aid.php', 'F', 'V', 'F', 'F', 'F', 'F', 'V', 'Saisie des notes et appréciations AID', '');
INSERT INTO droits VALUES ('/saisie/saisie_appreciations.php', 'F', 'V', 'F', 'F', 'F', 'F', 'V', 'Saisie des appréciations du bulletins', '');
INSERT INTO droits VALUES ('/saisie/saisie_avis.php', 'F', 'V', 'F', 'V', 'F', 'F', 'V', 'Saisie des avis du conseil de classe', '');
INSERT INTO droits VALUES ('/saisie/saisie_avis1.php', 'F', 'V', 'F', 'V', 'F', 'F', 'V', 'Saisie des avis du conseil de classe', '');
INSERT INTO droits VALUES ('/saisie/saisie_avis2.php', 'F', 'V', 'F', 'V', 'F', 'F', 'V', 'Saisie des avis du conseil de classe', '');
INSERT INTO droits VALUES ('/saisie/saisie_notes.php', 'F', 'V', 'F', 'F', 'F', 'F', 'V', 'Saisie des notes du bulletins', '');
INSERT INTO droits VALUES ('/saisie/traitement_csv.php', 'F', 'V', 'F', 'F', 'F', 'F', 'V', 'Saisie des notes du bulletins', '');
INSERT INTO droits VALUES ('/utilisateurs/change_pwd.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des utilisateurs', '');
INSERT INTO droits VALUES ('/utilisateurs/help.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des utilisateurs', '');
INSERT INTO droits VALUES ('/utilisateurs/import_prof_csv.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des utilisateurs', '');
INSERT INTO droits VALUES ('/utilisateurs/impression_bienvenue.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des utilisateurs', '');
INSERT INTO droits VALUES ('/utilisateurs/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des utilisateurs', '');
INSERT INTO droits VALUES ('/utilisateurs/reset_passwords.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Réinitialisation des mots de passe', '');
INSERT INTO droits VALUES ('/utilisateurs/modify_user.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des utilisateurs', '');
INSERT INTO droits VALUES ('/utilisateurs/mon_compte.php', 'V', 'V', 'V', 'V', 'V', 'V', 'V', 'Gestion du compte (informations personnelles, mot de passe, ...)', '');
INSERT INTO droits VALUES ('/visualisation/classe_classe.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Visualisation graphique des résultats scolaires', '');
INSERT INTO droits VALUES ('/visualisation/eleve_classe.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Visualisation graphique des résultats scolaires', '');
INSERT INTO droits VALUES ('/visualisation/eleve_eleve.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Visualisation graphique des résultats scolaires', '');
INSERT INTO droits VALUES ('/visualisation/evol_eleve_classe.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Visualisation graphique des résultats scolaires', '');
INSERT INTO droits VALUES ('/visualisation/evol_eleve.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Visualisation graphique des résultats scolaires', '');
INSERT INTO droits VALUES ('/visualisation/index.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Visualisation graphique des résultats scolaires', '');
INSERT INTO droits VALUES ('/visualisation/stats_classe.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Visualisation graphique des résultats scolaires', '');
INSERT INTO droits VALUES ('/classes/classes_param.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des classes', '');
INSERT INTO droits VALUES ('/fpdf/imprime_pdf.php', 'V', 'V', 'V', 'V', 'F', 'F', 'V', '', '');
INSERT INTO droits VALUES ('/etablissements/import_etab_csv.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Configuration et gestion des établissements', '');
INSERT INTO droits VALUES ('/saisie/import_app_cons.php', 'F', 'V', 'F', 'V', 'F', 'F', 'F', 'Importation csv des avis du conseil de classe', '');
INSERT INTO droits VALUES ('/messagerie/index.php', 'V', 'F', 'F', 'V', 'F', 'F', 'F', 'Gestion de la messagerie', '');
INSERT INTO droits VALUES ('/absences/import_absences_gep.php', 'F', 'F', 'V', 'F', 'F', 'F', 'V', 'Saisie des absences', '');
INSERT INTO droits VALUES ('/absences/seq_gep_absences.php', 'F', 'F', 'V', 'F', 'F', 'F', 'V', 'Saisie des absences', '');
INSERT INTO droits VALUES ('/utilitaires/clean_tables.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Maintenance', '');
INSERT INTO droits VALUES ('/gestion/contacter_admin.php', 'V', 'V', 'V', 'V', 'V', 'V', 'V', '', '');
INSERT INTO droits VALUES ('/mod_absences/gestion/gestion_absences.php', 'F', 'F', 'V', 'F', 'F', 'F', 'F', 'Gestion des absences', '');
INSERT INTO droits VALUES ('/mod_absences/gestion/impression_absences.php', 'F', 'F', 'V', 'F', 'F', 'F', 'F', 'Gestion des absences', '');
INSERT INTO droits VALUES ('/mod_absences/gestion/select.php', 'F', 'F', 'V', 'F', 'F', 'F', 'F', 'Gestion des absences', '');
INSERT INTO droits VALUES ('/mod_absences/gestion/ajout_ret.php', 'F', 'F', 'V', 'F', 'F', 'F', 'F', 'Gestion des absences', '');
INSERT INTO droits VALUES ('/mod_absences/gestion/ajout_dip.php', 'F', 'F', 'V', 'F', 'F', 'F', 'F', 'Gestion des absences', '');
INSERT INTO droits VALUES ('/mod_absences/gestion/ajout_inf.php', 'F', 'F', 'V', 'F', 'F', 'F', 'F', 'Gestion des absences', '');
INSERT INTO droits VALUES ('/mod_absences/gestion/ajout_abs.php', 'F', 'F', 'V', 'F', 'F', 'F', 'F', 'Gestion des absences', '');
INSERT INTO droits VALUES ('/mod_absences/gestion/bilan_absence.php', 'F', 'F', 'V', 'F', 'F', 'F', 'F', 'Gestion des absences', '');
INSERT INTO droits VALUES ('/mod_absences/gestion/bilan.php', 'F', 'F', 'V', 'F', 'F', 'F', 'F', 'Gestion des absences', '');
INSERT INTO droits VALUES ('/mod_absences/gestion/lettre_aux_parents.php', 'F', 'F', 'V', 'F', 'F', 'F', 'F', 'Gestion des absences', '');
INSERT INTO droits VALUES ('/mod_absences/lib/tableau.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', '', '');
INSERT INTO droits VALUES ('/mod_absences/admin/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Administration du module absences', '');
INSERT INTO droits VALUES ('/mod_absences/admin/admin_motifs_absences.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Administration du module absences', '');
INSERT INTO droits VALUES ('/mod_absences/admin/admin_periodes_absences.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Administration du module absences', '');
INSERT INTO droits VALUES ('/mod_absences/lib/liste_absences.php', 'F', 'V', 'V', 'F', 'F', 'F', 'F', '', '');
INSERT INTO droits VALUES ('/mod_absences/lib/graphiques.php', 'F', 'F', 'V', 'F', 'F', 'F', 'F', '', '');
INSERT INTO droits VALUES ('/mod_absences/professeurs/prof_ajout_abs.php', 'F', 'V', 'F', 'F', 'F', 'F', 'F', 'Ajout des absences en classe', '');
INSERT INTO droits VALUES ('/mod_absences/admin/admin_actions_absences.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Gestion des actions absences', '');
INSERT INTO droits VALUES ('/mod_trombinoscopes/trombinoscopes.php', 'F', 'V', 'V', 'F', 'F', 'F', 'F', 'Visualiser le trombinoscope', '');
INSERT INTO droits VALUES ('/mod_trombinoscopes/trombi_impr.php', 'F', 'V', 'V', 'F', 'F', 'F', 'F', 'Visualiser le trombinoscope', '');
INSERT INTO droits VALUES ('/mod_trombinoscopes/trombinoscopes_admin.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Administration du trombinoscope', '');
INSERT INTO `droits` VALUES ('/cahier_notes/visu_toutes_notes2.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Visualisation des moyennes des carnets de notes', '');
INSERT INTO `droits` VALUES ('/cahier_notes/index2.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Visualisation des moyennes des carnets de notes', '');
INSERT INTO `droits` VALUES ('/utilitaires/verif_groupes.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Vérification des incohérences d appartenances à des groupes', '');
INSERT INTO `droits` VALUES ('/referencement.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Référencement de Gepi sur la base centralisée des utilisateurs de Gepi', '');
INSERT INTO ct_types_documents VALUES (1, 'JPEG', 'jpg', 'oui');
INSERT INTO ct_types_documents VALUES (2, 'PNG', 'png', 'oui');
INSERT INTO ct_types_documents VALUES (3, 'GIF', 'gif', 'oui');
INSERT INTO ct_types_documents VALUES (4, 'BMP', 'bmp', 'oui');
INSERT INTO ct_types_documents VALUES (5, 'Photoshop', 'psd', 'oui');
INSERT INTO ct_types_documents VALUES (6, 'TIFF', 'tif', 'oui');
INSERT INTO ct_types_documents VALUES (7, 'AIFF', 'aiff', 'oui');
INSERT INTO ct_types_documents VALUES (8, 'Windows Media', 'asf', 'oui');
INSERT INTO ct_types_documents VALUES (9, 'Windows Media', 'avi', 'oui');
INSERT INTO ct_types_documents VALUES (10, 'Midi', 'mid', 'oui');
INSERT INTO ct_types_documents VALUES (12, 'QuickTime', 'mov', 'oui');
INSERT INTO ct_types_documents VALUES (13, 'MP3', 'mp3', 'oui');
INSERT INTO ct_types_documents VALUES (14, 'MPEG', 'mpg', 'oui');
INSERT INTO ct_types_documents VALUES (15, 'Ogg', 'ogg', 'oui');
INSERT INTO ct_types_documents VALUES (16, 'QuickTime', 'qt', 'oui');
INSERT INTO ct_types_documents VALUES (17, 'RealAudio', 'ra', 'oui');
INSERT INTO ct_types_documents VALUES (18, 'RealAudio', 'ram', 'oui');
INSERT INTO ct_types_documents VALUES (19, 'RealAudio', 'rm', 'oui');
INSERT INTO ct_types_documents VALUES (20, 'Flash', 'swf', 'oui');
INSERT INTO ct_types_documents VALUES (21, 'WAV', 'wav', 'oui');
INSERT INTO ct_types_documents VALUES (22, 'Windows Media', 'wmv', 'oui');
INSERT INTO ct_types_documents VALUES (23, 'Adobe Illustrator', 'ai', 'oui');
INSERT INTO ct_types_documents VALUES (24, 'BZip', 'bz2', 'oui');
INSERT INTO ct_types_documents VALUES (25, 'C source', 'c', 'oui');
INSERT INTO ct_types_documents VALUES (26, 'Debian', 'deb', 'oui');
INSERT INTO ct_types_documents VALUES (27, 'Word', 'doc', 'oui');
INSERT INTO ct_types_documents VALUES (29, 'LaTeX DVI', 'dvi', 'oui');
INSERT INTO ct_types_documents VALUES (30, 'PostScript', 'eps', 'oui');
INSERT INTO ct_types_documents VALUES (31, 'GZ', 'gz', 'oui');
INSERT INTO ct_types_documents VALUES (32, 'C header', 'h', 'oui');
INSERT INTO ct_types_documents VALUES (33, 'HTML', 'html', 'oui');
INSERT INTO ct_types_documents VALUES (34, 'Pascal', 'pas', 'oui');
INSERT INTO ct_types_documents VALUES (35, 'PDF', 'pdf', 'oui');
INSERT INTO ct_types_documents VALUES (36, 'PowerPoint', 'ppt', 'oui');
INSERT INTO ct_types_documents VALUES (37, 'PostScript', 'ps', 'oui');
INSERT INTO ct_types_documents VALUES (38, 'gr', 'gr', 'oui');
INSERT INTO ct_types_documents VALUES (39, 'RTF', 'rtf', 'oui');
INSERT INTO ct_types_documents VALUES (40, 'StarOffice', 'sdd', 'oui');
INSERT INTO ct_types_documents VALUES (41, 'StarOffice', 'sdw', 'oui');
INSERT INTO ct_types_documents VALUES (42, 'Stuffit', 'sit', 'oui');
INSERT INTO ct_types_documents VALUES (43, 'OpenOffice Calc', 'sxc', 'oui');
INSERT INTO ct_types_documents VALUES (44, 'OpenOffice Impress', 'sxi', 'oui');
INSERT INTO ct_types_documents VALUES (45, 'OpenOffice', 'sxw', 'oui');
INSERT INTO ct_types_documents VALUES (46, 'LaTeX', 'tex', 'oui');
INSERT INTO ct_types_documents VALUES (47, 'TGZ', 'tgz', 'oui');
INSERT INTO ct_types_documents VALUES (48, 'texte', 'txt', 'oui');
INSERT INTO ct_types_documents VALUES (49, 'GIMP multi-layer', 'xcf', 'oui');
INSERT INTO ct_types_documents VALUES (50, 'Excel', 'xls', 'oui');
INSERT INTO ct_types_documents VALUES (51, 'XML', 'xml', 'oui');
INSERT INTO ct_types_documents VALUES (52, 'Zip', 'zip', 'oui');
INSERT INTO ct_types_documents VALUES (53, 'Texte OpenDocument', 'odt', 'oui');
INSERT INTO ct_types_documents VALUES (54, 'Classeur OpenDocument', 'ods', 'oui');
INSERT INTO ct_types_documents VALUES (55, 'Présentation OpenDocument', 'odp', 'oui');
INSERT INTO ct_types_documents VALUES (56, 'Dessin OpenDocument', 'odg', 'oui');
INSERT INTO ct_types_documents VALUES (57, 'Base de données OpenDocument', 'odb', 'oui');
INSERT INTO absences_creneaux VALUES (1, 'M1', '08:00:00', '08:55:00');
INSERT INTO absences_creneaux VALUES (2, 'M2', '08:55:00', '09:50:00');
INSERT INTO absences_creneaux VALUES (3, 'M3', '10:05:00', '11:00:00');
INSERT INTO absences_creneaux VALUES (4, 'M4', '11:00:00', '11:55:00');
INSERT INTO absences_creneaux VALUES (5, 'S1', '13:30:00', '14:25:00');
INSERT INTO absences_creneaux VALUES (6, 'S2', '14:25:00', '15:20:00');
INSERT INTO absences_creneaux VALUES (7, 'S3', '15:35:00', '16:30:00');
INSERT INTO absences_creneaux VALUES (8, 'S4', '16:30:00', '17:30:00');
INSERT INTO absences_creneaux VALUES (32, 'M5', '11:55:00', '12:30:00');
INSERT INTO absences_creneaux VALUES (31, 'P1', '09:50:00', '10:05:00');
INSERT INTO absences_creneaux VALUES (33, 'R', '12:00:00', '13:00:00');
INSERT INTO absences_creneaux VALUES (34, 'R1', '13:00:00', '13:30:00');
INSERT INTO absences_creneaux VALUES (35, 'P2', '15:20:00', '15:35:00');
INSERT INTO absences_creneaux VALUES (36, 'S5', '17:30:00', '18:25:00');
INSERT INTO absences_motifs VALUES (1, 'A', 'Aucun motif');
INSERT INTO absences_motifs VALUES (2, 'AS', 'Accident sport');
INSERT INTO absences_motifs VALUES (3, 'AT', 'Absent en retenue');
INSERT INTO absences_motifs VALUES (4, 'C', 'Dans la cour');
INSERT INTO absences_motifs VALUES (5, 'CF', 'Convenances familiales');
INSERT INTO absences_motifs VALUES (6, 'CO', 'Convocation bureau');
INSERT INTO absences_motifs VALUES (7, 'CS', 'Compétition sportive');
INSERT INTO absences_motifs VALUES (8, 'DI', 'Dispense d''E.P.S.');
INSERT INTO absences_motifs VALUES (9, 'ET', 'Erreur d''emploi du temps');
INSERT INTO absences_motifs VALUES (10, 'EX', 'Examen');
INSERT INTO absences_motifs VALUES (11, 'H', 'Hospitalisation');
INSERT INTO absences_motifs VALUES (12, 'JP', 'Justification par le Principal');
INSERT INTO absences_motifs VALUES (13, 'MA', 'Maladie');
INSERT INTO absences_motifs VALUES (14, 'OR', 'Conseiller');
INSERT INTO absences_motifs VALUES (15, 'PR', 'Réveil');
INSERT INTO absences_motifs VALUES (16, 'RC', 'Refus de venir en cours');
INSERT INTO absences_motifs VALUES (17, 'RE', 'Renvoi');
INSERT INTO absences_motifs VALUES (18, 'RT', 'Présent en retenue');
INSERT INTO absences_motifs VALUES (19, 'RV', 'Renvoi du cours');
INSERT INTO absences_motifs VALUES (20, 'SM', 'Refus de justification');
INSERT INTO absences_motifs VALUES (21, 'SP', 'Sortie pédagogique');
INSERT INTO absences_motifs VALUES (22, 'ST', 'Stage à l''extérieur');
INSERT INTO absences_motifs VALUES (23, 'T', 'Téléphone');
INSERT INTO absences_motifs VALUES (24, 'TR', 'Transport');
INSERT INTO absences_motifs VALUES (25, 'VM', 'Visite médicale');
INSERT INTO absences_motifs VALUES (26, 'IN', 'Infirmerie');
INSERT INTO `droits` VALUES ('/utilisateurs/tab_profs_matieres.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Affectation des matieres aux professeurs', '');
INSERT INTO `droits` VALUES ('/matieres/matieres_csv.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Importation des matières depuis un fichier CSV', '');
INSERT INTO `droits` VALUES ('/groupes/edit_class_grp_lot.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Gestion des enseignements simples par lot.', '');
INSERT INTO `droits` VALUES ('/init_dbf_sts/clean_tables.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO `droits` VALUES ('/init_dbf_sts/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO `droits` VALUES ('/init_dbf_sts/init_options.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO `droits` VALUES ('/init_dbf_sts/responsables.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO `droits` VALUES ('/init_dbf_sts/step1.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO `droits` VALUES ('/init_dbf_sts/step2.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO `droits` VALUES ('/init_dbf_sts/step3.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO `droits` VALUES ('/init_dbf_sts/disciplines_csv.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO `droits` VALUES ('/init_dbf_sts/prof_disc_classe_csv.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO `droits` VALUES ('/init_dbf_sts/prof_csv.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO `droits` VALUES ('/init_dbf_sts/lecture_xml_sts_emp.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO `droits` VALUES ('/init_dbf_sts/init_pp.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO `droits` VALUES ('/init_dbf_sts/save_csv.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation de l''année scolaire', '');
INSERT INTO `droits` VALUES ('/groupes/visu_profs_class.php', 'V', 'V', 'V', 'V', 'F', 'F', 'F', 'Visualisation des équipes pédagogiques', '');
INSERT INTO `droits` VALUES ('/groupes/popup.php', 'V', 'V', 'V', 'V', 'F', 'F', 'F', 'Visualisation des équipes pédagogiques', '');
INSERT INTO `matieres_categories` VALUES (1, 'Autres', 'Autres', '5');
INSERT INTO droits VALUES ('/visualisation/affiche_eleve.php', 'F', 'V', 'V', 'V', 'V', 'V', 'F', 'Visualisation graphique des résultats scolaires', '');
INSERT INTO droits VALUES ('/visualisation/draw_graphe.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Visualisation graphique des résultats scolaires', '');
INSERT INTO setting VALUES ('gepi_denom_boite','boite');
INSERT INTO setting VALUES ('gepi_denom_boite_genre','f');
INSERT INTO droits VALUES ('/groupes/mes_listes.php', 'V', 'V', 'V', 'V', 'F', 'F', 'F', 'Accès aux CSV des listes d élèves', '');
INSERT INTO droits VALUES ('/groupes/get_csv.php', 'F', 'V', 'V', 'V', 'F', 'F', 'V', 'Génération de CSV élèves', '');
INSERT INTO droits VALUES ('/visualisation/choix_couleurs.php', 'V', 'F', 'F', 'V', 'F', 'F', 'F', 'Choix des couleurs des graphiques des résultats scolaires', '');
INSERT INTO droits VALUES ('/visualisation/couleur.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Choix d une couleur pour le graphique des résultats scolaires', '');
INSERT INTO droits VALUES ('/gestion/config_prefs.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Définition des préférences d utilisateurs', '');
INSERT INTO setting VALUES ('addressblock_font_size', '12');
INSERT INTO setting VALUES ('addressblock_logo_etab_prop', '50');
INSERT INTO setting VALUES ('addressblock_classe_annee', '35');
INSERT INTO setting VALUES ('bull_ecart_bloc_nom', '1');
INSERT INTO setting VALUES ('addressblock_debug', 'n');
INSERT INTO droits VALUES ('/utilitaires/recalcul_moy_conteneurs.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Correction des moyennes des conteneurs', '');
INSERT INTO droits VALUES ('/saisie/commentaires_types.php', 'V', 'V', 'V', 'V', 'F', 'F', 'V', 'Saisie de commentaires-types', '');
INSERT INTO droits VALUES ('/mod_absences/lib/fiche_eleve.php', 'F', 'V', 'V', 'F', 'F', 'F', 'F', 'Fiche du suivie de l''élève', '');
INSERT INTO droits VALUES ('/cahier_notes/releve_pdf.php', 'V', 'V', 'F', 'V', 'F', 'F', 'V', 'Relevé de note au format PDF', '');
INSERT INTO droits VALUES ('/impression/parametres_impression_pdf.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Impression des listes PDF; réglage des paramètres', '');
INSERT INTO droits VALUES ('/impression/impression_serie.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Impression des listes (PDF) en série', '');
INSERT INTO droits VALUES ('/impression/impression.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Impression rapide d une listes (PDF) ', '');
INSERT INTO droits VALUES ('/impression/liste_pdf.php', 'F', 'V', 'V', 'V', 'F', 'F', 'F', 'Impression des listes (PDF)', '');
INSERT INTO droits VALUES ('/init_xml/lecture_xml_sconet.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation année scolaire', '');
INSERT INTO droits VALUES ('/init_xml/init_pp.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation année scolaire', '');
INSERT INTO droits VALUES ('/init_xml/clean_tables.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation année scolaire', '');
INSERT INTO droits VALUES ('/init_xml/step2.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation année scolaire', '');
INSERT INTO droits VALUES ('/init_xml/step1.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation année scolaire', '');
INSERT INTO droits VALUES ('/init_xml/disciplines_csv.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation année scolaire', '');
INSERT INTO droits VALUES ('/init_xml/prof_disc_classe_csv.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation année scolaire', '');
INSERT INTO droits VALUES ('/init_xml/lecture_xml_sts_emp.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation année scolaire', '');
INSERT INTO droits VALUES ('/init_xml/prof_csv.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation année scolaire', '');
INSERT INTO droits VALUES ('/init_xml/index.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation année scolaire', '');
INSERT INTO droits VALUES ('/init_xml/init_options.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation année scolaire', '');
INSERT INTO droits VALUES ('/init_xml/save_csv.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation année scolaire', '');
INSERT INTO droits VALUES ('/init_xml/responsables.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation année scolaire', '');
INSERT INTO droits VALUES ('/init_xml/step3.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Initialisation année scolaire', '');
INSERT INTO droits VALUES ('/responsables/maj_import.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Mise à jour depuis Sconet', '');
INSERT INTO droits VALUES ('/responsables/conversion.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Conversion des données responsables', '');
INSERT INTO droits VALUES ('/utilisateurs/create_responsable.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Création des utilisateurs au statut responsable', '');
INSERT INTO droits VALUES ('/utilisateurs/create_eleve.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Création des utilisateurs au statut responsable', '');
INSERT INTO droits VALUES ('/utilisateurs/edit_responsable.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Edition des utilisateurs au statut responsable', '');
INSERT INTO droits VALUES ('/utilisateurs/edit_eleve.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Edition des utilisateurs au statut élève', '');
INSERT INTO droits VALUES ('/cahier_texte/consultation.php', 'F', 'F', 'F', 'F', 'V', 'V', 'F', 'Consultation des cahiers de texte', '');
INSERT INTO droits VALUES ('/cahier_texte/see_all.php', 'F', 'F', 'F', 'F', 'V', 'V', 'F', 'Consultation des cahiers de texte', '');
INSERT INTO droits VALUES ('/gestion/droits_acces.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Paramétrage des droits d accès', '');
INSERT INTO setting VALUES ('GepiAccesReleveEleve', 'yes');
INSERT INTO setting VALUES ('GepiAccesCahierTexteEleve', 'yes');
INSERT INTO setting VALUES ('GepiAccesReleveParent', 'yes');
INSERT INTO setting VALUES ('GepiAccesCahierTexteParent', 'yes');
INSERT INTO setting VALUES ('enable_password_recovery', 'no');
INSERT INTO setting VALUES ('GepiPasswordReinitProf', 'no');
INSERT INTO setting VALUES ('GepiPasswordReinitScolarite', 'no');
INSERT INTO setting VALUES ('GepiPasswordReinitCpe', 'no');
INSERT INTO setting VALUES ('GepiPasswordReinitAdmin', 'no');
INSERT INTO setting VALUES ('GepiPasswordReinitEleve', 'yes');
INSERT INTO setting VALUES ('GepiPasswordReinitParent', 'yes');
INSERT INTO setting VALUES ('cahier_texte_acces_public', 'no');
INSERT INTO setting VALUES ('GepiAccesEquipePedaEleve', 'yes');
INSERT INTO setting VALUES ('GepiAccesEquipePedaEmailEleve', 'no');
INSERT INTO setting VALUES ('GepiAccesEquipePedaParent', 'yes');
INSERT INTO setting VALUES ('GepiAccesEquipePedaEmailParent', 'no');
INSERT INTO droits VALUES ('/groupes/visu_profs_eleve.php', 'F', 'F', 'F', 'F', 'V', 'V', 'F', 'Consultation équipe pédagogique', '');
INSERT INTO setting VALUES ('GepiAccesBulletinSimpleParent', 'yes');
INSERT INTO setting VALUES ('GepiAccesBulletinSimpleEleve', 'yes');
INSERT INTO droits VALUES ('/saisie/impression_avis.php', 'F', 'V', 'F', 'V', 'F', 'F', 'F', 'Impression des avis trimestrielles des conseils de classe.', '');
INSERT INTO droits VALUES ('/impression/avis_pdf.php', 'F', 'V', 'F', 'V', 'F', 'F', 'F', 'Impression des avis trimestrielles des conseils de classe. Module PDF', '');
INSERT INTO droits VALUES ('/impression/parametres_impression_pdf_avis.php', 'F', 'V', 'F', 'V', 'F', 'F', 'F', 'Impression des avis conseil classe PDF; reglage des parametres', '');
INSERT INTO setting VALUES ('GepiAccesGraphEleve', 'yes');
INSERT INTO setting VALUES ('GepiAccesGraphParent', 'yes');
INSERT INTO droits VALUES ('/utilisateurs/password_csv.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F', 'Export des identifiants et mots de passe en csv', '');
INSERT INTO droits VALUES ('/impression/password_pdf.php', 'V', 'F', 'F', 'F', 'F', 'F', 'F','Impression des identifiants et des mots de passe en PDF', '');
INSERT INTO `setting` (`NAME`, `VALUE`) VALUES ('choix_bulletin', '1');
